project:
  type: website
  output-dir: docs

website:
  title: "UchidaMizuki"
  site-url: "https://uchidamizuki.github.io"
  favicon: logo.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/UchidaMizuki
      - text: SoundCloud
        href: https://soundcloud.com/uchidamizuki
  google-analytics: "G-VW3C30XP8C"

format:
  html:
    theme: simplex

editor: visual

comments:
  giscus: 
    repo: UchidaMizuki/UchidaMizuki.github.io